### ISSUE TITLE
No modbus.base_platform in recent versions of Home Assistant

### ISSUE THREAD

**Issue by asinpk** [nos86/hacs-modbus-logo#32]
## System Information

version | core-2024.10.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.46-haos
arch | x86_64
timezone | Asia/Kamchatka
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4970
Installed Version | 2.0.1
Stage | running
Available Repositories | 1430
Downloaded Repositories | 4

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.10.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 30.8 GB
disk_used | 4.2 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.15.0), File editor (5.8.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 1 октября 2024 г. в 21:47
-- | --
current_recorder_run | 8 октября 2024 г. в 17:59
estimated_db_size | 3.66 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 0.7.20
-- | --
can_reach_server | ok
can_reach_spec | ok
logged_accounts | 0
total_devices | 0

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Some time ago in PR https://github.com/home-assistant/core/pull/126104/commits the "base_platform.py" module was moved to "entity.py" and now integration startup failed with error "No module named 'homeassistant.components.modbus.base_platform'".

My modbus config:
``` yaml
modbus_logo:
  - name: modbus_pplc
    type: serial
    port: /dev/ttyUSB0
    baudrate: 115200
    bytesize: 8
    method: rtu
    parity: N
    stopbits: 1
    lights:
      - name: pplc_light_basement
        slave: 1
        address: 0
        scan_interval: 1
        write_type: holding
        command_on: 1
        command_off: 0
        verify:
            input_type: holding
            address: 0
            state_on: 1
            state_off: 0
            sync: true
      - name: pplc_light_first_floor
        slave: 1
        address: 1
        scan_interval: 1
        write_type: holding
        command_on: 1
        command_off: 0
        verify:
            input_type: input
            address: 1
            state_on: 1
            state_off: 0
            sync: true
      - name: pplc_light_second_floor
        slave: 1
        address: 2
        scan_interval: 1
        write_type: holding
        command_on: 1
        command_off: 0
        verify:
            input_type: input
            address: 2
            state_on: 1
            state_off: 0
            sync: true
```

### Reproduction steps

1. Install recent HA
2. Install integration
3. Add some modbus switches/lights/etc.

### Debug logs

```text
2024-10-08 18:22:23.946 DEBUG (MainThread) [homeassistant.loader] Importing platforms for modbus_logo executor=['light'] loop=[] took 0.75s
2024-10-08 18:22:23.946 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform 'modbus_logo.light': Platform not found (No module named 'homeassistant.components.modbus.base_platform').
2024-10-08 18:22:23.952 DEBUG (MainThread) [homeassistant.loader] Importing platforms for modbus_logo executor=['switch'] loop=[] took 0.76s
2024-10-08 18:22:23.952 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform 'modbus_logo.switch': Platform not found (No module named 'homeassistant.components.modbus.base_platform').
```
